### ISSUE TITLE
Cant generate sitempa after setting 'enable_javascript' => true

### ISSUE THREAD

**Issue by lachie-92** [spatie/laravel-sitemap#328]
We have a few pages created using javascript which were not being generated in the sitempa, i looked around and was told to enable javascript, i now recieve the following error. I have installed puppeteer and still recieving the error. 

vagrant@homestead:~/code/dev-www.medlab.co/medlab$ php artisan sitemap:generate

```
Symfony\Component\Process\Exception\ProcessFailedException  : The command "PATH=$PATH:/usr/local/bin NODE_PATH=`npm root -g` node '/home/vagrant/code/dev-www.medlab.co/medlab/vendor/spatie/browsershot/src/../bin/browser.js' '{"url":"http:\/\/dev-www.medlab.test\/","action":"content","options":{"args":[],"viewport":{"width":800,"height":600}}}'" failed.

Exit Code: 1(General error)

Working directory: /home/vagrant/code/dev-www.medlab.co/medlab

Output:
================


Error Output:
================
Error: Failed to launch the browser process!
/home/vagrant/code/dev-www.medlab.co/medlab/node_modules/puppeteer/.local-chromium/linux-782078/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/home/vagrant/code/dev-www.medlab.co/medlab/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
    at Interface.<anonymous> (/home/vagrant/code/dev-www.medlab.co/medlab/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:183:68)
    at Interface.emit (events.js:323:22)
    at Interface.close (readline.js:409:8)
    at Socket.onend (readline.js:187:10)
    at Socket.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)


  at /home/vagrant/code/dev-www.medlab.co/medlab/vendor/spatie/browsershot/src/Browsershot.php:738
    734|         if ($process->getExitCode() === 2) {
    735|             throw new ElementNotFound($this->additionalOptions['selector']);
    736|         }
    737| 
  > 738|         throw new ProcessFailedException($process);
    739|     }
    740| 
    741|     protected function getFullCommand(array $command)
    742|     {

  Exception trace:

  1   Spatie\Browsershot\Browsershot::callBrowser()
      /home/vagrant/code/dev-www.medlab.co/medlab/vendor/spatie/browsershot/src/Browsershot.php:504

  2   Spatie\Browsershot\Browsershot::bodyHtml()
      /home/vagrant/code/dev-www.medlab.co/medlab/vendor/spatie/crawler/src/Handlers/CrawlRequestFulfilled.php:113

  Please use the argument -v to see more details.
```

**Comment by jonathan-bird** [comment]
Try installing puppeteer (`npm install puppeteer  --save`) and re-run.

**Comment by jonathan-bird** [comment]
You need to install it globally for ubuntu: Check these instructions: https://github.com/spatie/browsershot#requirements
